### 1 Datentypen
## 1.1 Listen

Eine Liste ist eine Aneinanderreihung von beliebigen Pythonobjekten. Einige Eigenschaften von Listen lernst Du
kennen, wenn Du folgendes Programm ausfuehrst:


In [6]:
lst=[1,2.0,'Klaus']
print(type(lst))
print(lst)
i=1
print('Das ',i,'. Element der Liste ist',lst[1])
lst[1]='Peter'
print(lst)
#der Liste kann man Elemente hinzuf¨ugen:
lst.append(7)
print(lst)
lst.append("NECRO")
print(lst)
#man kann auch ein Element rausl¨oschen, etwa Peter
del lst[1]
print('Liste ohne Peter:',lst)
del lst[2]
print("Liste ohne 7:",lst)
#Die Anzahl der Elemente in einer Liste erh¨alt man so:
l=len(lst)
print('Die Liste hat',l,'Elemente')

<class 'list'>
[1, 2.0, 'Klaus']
Das  1 . Element der Liste ist 2.0
[1, 'Peter', 'Klaus']
[1, 'Peter', 'Klaus', 7]
[1, 'Peter', 'Klaus', 7, 'NECRO']
Liste ohne Peter: [1, 'Klaus', 7, 'NECRO']
Liste ohne 7: [1, 'Klaus', 'NECRO']
Die Liste hat 3 Elemente


Beachte: Die Objekte in einer Liste k¨onnen einen Typ haben: integer (wie 1 unserem Beispiel) , string (wie Klaus),
float (wie 2.0),...


### 1.2 Arrays
Listen sind praktisch. Aber sie haben eine Nachteil: Man kann mit ihnen nicht so gut Mathematik treiben. F¨ur
Mathematik, Physik, Technik ... ben¨otigen wir das Modul NumPy. NumPy ist ein Python-Modul, mit dem du
effizient mit großen Zahlenmengen, Tabellen und mathematischen Berechnungen arbeiten kannst – praktisch, wenn
Du physikalische Simulationen durchf¨uhren m¨ochtest.
Den wichtigsten Datentyp in Numpy stellt das Array dar. Eine Array ist so ¨ahnlich wie eine Liste, mit dem großen
Unterschied, dass bei einem Array alle Elemente von gleichen Datentyp sein m¨ussen.
Beispiel Stell dir vor, du willst die Noten deiner Freunde in Mathe speichern: 2, 3, 1, 4, 2. Mit einem Array kannst
du das so machen:


In [8]:
import numpy as np
noten = np.array([2, 3, 1, 4, 2])

print(noten[0]) # Ausgabe: 2
print(np.mean(noten))

2
2.4


Jetzt hast du alle Noten in einer einzigen Variable gespeichert - wie in einem Notizbuch mit nummerierten Seiten.
Du kannst z.B. die erste Note abrufen mit:
print(noten[0]) # Ausgabe: 2

Oder den Durchschnitt berechnen:
print(np.mean(noten))

In [7]:
import numpy as np
Buecher = np.array(["Faust","Darth Bane","Revan","Plagueis"])

print(Buecher[3])

Plagueis


Das war ein Beispiel f¨ur Mathematik mit arrays!
Praktisch sind arrays auch f¨ur Funktionen:


In [9]:
x=np.array([-3,-1,0,-1,2])
y=x*x
print(y)


[9 1 0 1 4]


In [11]:
x=np.array([-9,-4,-1,0,5,9,15])
y=x*x
print(y)

[ 81  16   1   0  25  81 225]


Jetzt hast Du in einem Rutsch alle Elemente von x quadriert.
Passiert, wenn Du


In [12]:
x=np.array([-3,-1,0,-1,2])
y=x+1
print(y)
#oder
y2=x*2
print(y2)

[-2  0  1  0  3]
[-6 -2  0 -2  4]


In [13]:
x=np.array([-9,-4,-1,0,5,9,15])
y=x+1
print(y)
#oder
y2=x*2
print(y2)

[-8 -3  0  1  6 10 16]
[-18  -8  -2   0  10  18  30]


machst?
Vielleicht ist Dir aufgefallen, dass Du ein array erzeugt hast, indem Du die Liste [−3, −1, 0, −1, 2] in ein Array
umgewandelt hast. Das macht man oft, es gibt aber noch andere M¨oglichkeiten (siehe unten).
Erst noch ein paar n¨utzliche Array-Befehle:


In [ ]:
#erzeugen aus eine Liste
a=np.array([1.0,2.0,3.0,4.0,5.0,6.0])
print(a)
#Die Anzahl der Elemente erhaelt man so:
s=a.size
print(s)
i=0
print('Das ',i,'.Elemente ist',a[i])
i=3
print('Das ',i,'.Elemente ist',a[i])
#wichtig ist auch der Datentyp:
print('Datentyp:',a.dtype)


[1. 2. 3. 4. 5. 6.]
6
Das  0 .Elemente ist 1.0
Das  3 .Elemente ist 4.0
Datentyp: float64


Beim Datentyp muss man aufpassen: Wenn man das Array aus einer Liste erzeugt, so versucht NumPy, den Datentyp
des Arrays aus den in der Liste enthaltenen Daten abzuleiten. Sieh hier:


In [15]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1.0,2,4])
# Pruefe mit a.type und b.type den Datentyp
a[2]=42.7
b[2]=42.7
print(a)
print(b)
#gemein, gemein...


[ 1  2 42]
[ 1.   2.  42.7]


Was ist daran eigentlich gemein?

Erzeugen von Arrays In den bisherigen Beispielen wurde ein Array immer aus einer Liste erzeugt. Es gibt noch
andere Moeglichkeiten:

In [16]:
import numpy as np
#np.arange(Anfang,Ende,Schrittweite)
a=np.arange(1,20,2)
print(a)
#Erzeuge mit np.arange das Array [4,7,10,13,16]
# Es geht aber auch so:
#np.linespace(Anfang,Ende,Anzahl)
a=np.linspace(1,21,5)
a=np.linspace(1,21,7)
print(a)
print(b)
#Wenn man nur Nuller will,kann man schreiben
n=np.zeros(10)
#einsen erh¨alt man so
eins=np.ones(100)
#Zehner sind dann
zehn=eins*10
print(zehn)
#lauter wurzelzweier k¨onnte man so erzeugen
sqrt2=np.sqrt(np.ones(10)*2)


[ 1  3  5  7  9 11 13 15 17 19]
[ 1.          4.33333333  7.66666667 11.         14.33333333 17.66666667
 21.        ]
[ 1.   2.  42.7]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


Aufgabe: Erzeuge das Array t mit Elementen von einschliesslich 0 bis einschliesslich 1 mit der Schrittweite 0.1

In [22]:
import numpy as np
a=np.arange(0,1.1,0.1)
print(a)



[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### 2 Graphische Ausgabe mit matplotlib
In der Physik und in den Naturwissenschaften werden sehr h¨aufig Diagramm verwendet, die den Zusammenhang von
Gr¨oßen veranschaulicht. Z.B kann man die Geschwindigkeit eines Balls gegen die Zeit auftragen. Die Bibliothek Matplotlib bietet eine riesiges Reservoir an graphischen Darstellungsm¨oglichkeiten, wir werden aber nur wenige brauchen.
Hier findest Du ganz viele Beispiele: https://matplotlib.org/stable/gallery/index.html. Wenn ich nicht
weiß, wie man das Diagramm erzeugt, das ich im Kopf habe, schaue ich dort noch einem Beispiel, dass ungef¨ahr so
aus, wie ich es mir vorstelle.


Beispiel Es soll die Polynomfunktion $$f(x) = \frac{1}{4}(x+1)(x-3)^3$$ im Intervall [-2,4] dargestellt werden.
